language: python
python:
  - "3.7"
install: 
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests, e.g. python setup.py test
script:  nosetests --with-coverage --cover-package=match