package:
  name: match
  version: "0.2.1"

source:
  git_url: https://github.com/EducationalTestingService/match.git
  #git_tag: 0.1

requirements:
  build:
    - python
    - nltk
    - regex
  run:
    - python
    - nltk
    - regex

about:
  home: https://github.com/EducationalTestingService/match
  license: Apache 2.0
  summary: Obtain offsets of clean strings within messy text.