package:
  name: match
  version: "0.1"

source:
  git_url: https://github.com/EducationalTestingService/match.git
  #git_tag: 0.1

build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - nltk
    - regex

about:
  home: https://github.com/EducationalTestingService/match
  license: GPLv2
  summary: Obtain offsets of clean strings within messy text.