# -*- coding: utf-8 -*-

try:
    from itertools import izip as zip
except:
    pass

import sys

from nose.tools import eq_

from match import Match


# Excepts from blog entries from the CBC/Corporati corpus: http://ynada.com/cbc-corporati/
test_text = """It'? ?s hard to believe but Dreamforce is less than a week away!In preparation for salesforce. com'? ?s biggest event of the year, we'? ?ve cataloged all 150 breakout sessions on the Successforce. com site.   During the conference you can use this guide to plan your day. You can navigate by track or choose between the various session offered during a given time slot. On the session detail pages you'? ?ll find a list of speakers and their respective companies. We also have a spot where you can leave comments about the session, or post questions you'? ?d like to see the presenter cover. (Dreamforce Comments Feed)To bring Dreamforce to those who can't make it, we try to post much of the content online. Last year we had over 50k downloads after the conference, and this year we expect a dramatic increase this year as we introduce video. In each of the 12 breakout rooms we'? ?ll be recording video so you can connect with the presenter and see all the amazing product demos. The first video will be posted on Wednesday October 11th with additional sessions posted to the site as they are produced. For those looking for immediate gratification, we are also planning on posting the PowerPoint slides and other resources referenced in the presentation on the session detail pages.  We'? ?ve got a fantastic week ahead. You won'? ?t want to miss it. Make your last minute travel plans and get registered today!Last Friday when the temperature resulted in an \air stagnation alert\ (I have no idea) . I should have been done on Saturday but had to add those few extra days back in (since the program is based on building on intervals) .I am happy to confirm that I ran for 28 minutes today (well, by running I mean jogging that looks slow but totally rocks my heart rate) . Tomorrow, I run thirty minutes and give myself a pat on the back (it's OK, I'm going to call it stretching) .  Happy Chinese New YearWishing everyone a HAPPY CHINESE NEW YEAR! Chapter One: Rise of the monkeyFor thousand of years , a stone had been absorbing the\ki\ of the heaven and earth , finally one day , it exploded and Mosaic Monkey ( M & M in short ) was borned. This crappy ideas of mosaic monkey (inspired by Monkey god and crayon shin) had been floating in my mind for a few months so finally today i decided to scanned 2 of sketches and make it into a illustration. More will come. ... Chapter two: Enter the monkeyMosaic Monkey decided to take down all the demons in the jungle to become the King of the jungle. Kazaaaaa! !! (* inspired by Bruce lee: enter the dragon )************************************************************************************Recently, i came across a advertisement on a bus stop, it wrote this \\No one can survive on the diets of hope! \ So true. ... ..Who can? ?"
"Filed under: AOLTed checks in on what people are calling the  \data Valdez. \ It so nice having Ted blogging, sometimes I feel like I'm alone on the front lines. I wish other senior executives would start blogging at AOL (hint, hint) --or at least commenting (you guys know you can post a comment to Ted's blog or my blog right? ). I have to be honest with y'all: it's hard times at AOL right now, that's for sure. Every couple of steps we take going forward (Netscape, TMZ, Live8, moving to the free model, AIM Pro, AIM Pages, free five gigs of backup, 40% growth of advertising for Q2--beating Yahoo, MapQuests API, AOL Uncut Video) , we seem to get hit back by something horrible like \the call\ or \the data Valdez. \ The truth is the company is moving forward, but these things create a horrible perception problem, and it has a real world impact in that it de-motivates my teams and it makes it so much harder to get new people into the company. Smart folks ask me about stuff like \the call\ when I try to recruit them for AOL, and I have to assure them it isn't gonna happen again. It's not easy, and I wish I could tell you I always win that fight--but I don't. I was so angry today that I had to get off my computer and do a three-mile run. I'm back at my desk but I'm still seething--how could this happen? ! Everyone is working so hard to get AOL on the right track, and it all gets forgotten when this kind of thing happens. I think I'm gonna take the rest of the week off from blogging as a \cool down\period. I don't want to say something I regret, and I don't want to become the spokesperson for the entire company--that's not my job and it's not my desire. I just want to build cool stuff with cool people I respect. To my team (and everyone at AOL) , keep fighting the good fight. Put your anger into your game and stay focused. The darkest hour is the one before the dawn. We're gonna get through this. [Note: AOL staffers can feel free to post their comments below--anonymous or on the record. I'll turn them on for you if you use a fake email. ]  La version RC1 d’Operations Manager 2007 est disponible depuis http://connect.microsoft.com

Les améliorations sur la beta 2 sont les suivantes :

·         Process d’installation amélioré

·         Améliorations de l’interface utilisateur

·         Mises à jour de packs d’administration et apparition du pack Active Directory

·         Serveur Gateway (je tente la traduction de passerelleJ) et utilisation de certificats pour les périphériques hors domaine

·         Support d’architecture utilisant plusieurs serveurs d’administration

·         Amélioration de la stabilité

Les prochaines étapes visent un lancement mondial à San Diego lors du prochain Microsoft Management Summit (MMS), en mars prochain."""

test_sentences = [
    [
        "It",
        "'",
        "??",
        "s",
        "hard",
        "to",
        "believe",
        "but",
        "Dreamforce",
        "is",
        "less",
        "than",
        "a",
        "week",
        "away",
        "!",
    ],
    ["In", "preparation", "for", "salesforce", "."],
    [
        "com",
        "'",
        "??",
        "s",
        "biggest",
        "event",
        "of",
        "the",
        "year",
        ",",
        "we",
        "'",
        "??",
        "ve",
        "cataloged",
        "all",
        "150",
        "breakout",
        "sessions",
        "on",
        "the",
        "Successforce",
        ".",
    ],
    ["com", "site", "."],
    [
        "During",
        "the",
        "conference",
        "you",
        "can",
        "use",
        "this",
        "guide",
        "to",
        "plan",
        "your",
        "day",
        ".",
    ],
    [
        "You",
        "can",
        "navigate",
        "by",
        "track",
        "or",
        "choose",
        "between",
        "the",
        "various",
        "session",
        "offered",
        "during",
        "a",
        "given",
        "time",
        "slot",
        ".",
    ],
    [
        "On",
        "the",
        "session",
        "detail",
        "pages",
        "you",
        "'",
        "??",
        "ll",
        "find",
        "a",
        "list",
        "of",
        "speakers",
        "and",
        "their",
        "respective",
        "companies",
        ".",
    ],
    [
        "We",
        "also",
        "have",
        "a",
        "spot",
        "where",
        "you",
        "can",
        "leave",
        "comments",
        "about",
        "the",
        "session",
        ",",
        "or",
        "post",
        "questions",
        "you",
        "'",
        "??",
        "d",
        "like",
        "to",
        "see",
        "the",
        "presenter",
        "cover",
        ".",
    ],
    ["-LRB-", "Dreamforce", "Comments", "Feed", "-RRB-"],
    [
        "To",
        "bring",
        "Dreamforce",
        "to",
        "those",
        "who",
        "ca",
        "n't",
        "make",
        "it",
        ",",
        "we",
        "try",
        "to",
        "post",
        "much",
        "of",
        "the",
        "content",
        "online",
        ".",
    ],
    [
        "Last",
        "year",
        "we",
        "had",
        "over",
        "50k",
        "downloads",
        "after",
        "the",
        "conference",
        ",",
        "and",
        "this",
        "year",
        "we",
        "expect",
        "a",
        "dramatic",
        "increase",
        "this",
        "year",
        "as",
        "we",
        "introduce",
        "video",
        ".",
    ],
    [
        "In",
        "each",
        "of",
        "the",
        "12",
        "breakout",
        "rooms",
        "we",
        "'",
        "??",
        "ll",
        "be",
        "recording",
        "video",
        "so",
        "you",
        "can",
        "connect",
        "with",
        "the",
        "presenter",
        "and",
        "see",
        "all",
        "the",
        "amazing",
        "product",
        "demos",
        ".",
    ],
    [
        "The",
        "first",
        "video",
        "will",
        "be",
        "posted",
        "on",
        "Wednesday",
        "October",
        "11th",
        "with",
        "additional",
        "sessions",
        "posted",
        "to",
        "the",
        "site",
        "as",
        "they",
        "are",
        "produced",
        ".",
    ],
    [
        "For",
        "those",
        "looking",
        "for",
        "immediate",
        "gratification",
        ",",
        "we",
        "are",
        "also",
        "planning",
        "on",
        "posting",
        "the",
        "PowerPoint",
        "slides",
        "and",
        "other",
        "resources",
        "referenced",
        "in",
        "the",
        "presentation",
        "on",
        "the",
        "session",
        "detail",
        "pages",
        ".",
    ],
    ["We", "'", "??", "ve", "got", "a", "fantastic", "week", "ahead", "."],
    ["You", "won", "'", "??", "t", "want", "to", "miss", "it", "."],
    [
        "Make",
        "your",
        "last",
        "minute",
        "travel",
        "plans",
        "and",
        "get",
        "registered",
        "today",
        "!",
    ],
    [
        "Last",
        "Friday",
        "when",
        "the",
        "temperature",
        "resulted",
        "in",
        "an",
        "\x07",
        "ir",
        "stagnation",
        "alert",
        "\\",
        "-LRB-",
        "I",
        "have",
        "no",
        "idea",
        "-RRB-",
        ".",
    ],
    [
        "I",
        "should",
        "have",
        "been",
        "done",
        "on",
        "Saturday",
        "but",
        "had",
        "to",
        "add",
        "those",
        "few",
        "extra",
        "days",
        "back",
        "in",
        "-LRB-",
        "since",
        "the",
        "program",
        "is",
        "based",
        "on",
        "building",
        "on",
        "intervals",
        "-RRB-",
        ".",
    ],
    [
        "I",
        "am",
        "happy",
        "to",
        "confirm",
        "that",
        "I",
        "ran",
        "for",
        "28",
        "minutes",
        "today",
        "-LRB-",
        "well",
        ",",
        "by",
        "running",
        "I",
        "mean",
        "jogging",
        "that",
        "looks",
        "slow",
        "but",
        "totally",
        "rocks",
        "my",
        "heart",
        "rate",
        "-RRB-",
        ".",
    ],
    [
        "Tomorrow",
        ",",
        "I",
        "run",
        "thirty",
        "minutes",
        "and",
        "give",
        "myself",
        "a",
        "pat",
        "on",
        "the",
        "back",
        "-LRB-",
        "it",
        "'s",
        "OK",
        ",",
        "I",
        "'m",
        "going",
        "to",
        "call",
        "it",
        "stretching",
        "-RRB-",
        ".",
    ],
    [
        "Happy",
        "Chinese",
        "New",
        "YearWishing",
        "everyone",
        "a",
        "HAPPY",
        "CHINESE",
        "NEW",
        "YEAR",
        "!",
    ],
    [
        "Chapter",
        "One",
        ":",
        "Rise",
        "of",
        "the",
        "monkeyFor",
        "thousand",
        "of",
        "years",
        ",",
        "a",
        "stone",
        "had",
        "been",
        "absorbing",
        "the",
        "\\",
        "ki",
        "\\",
        "of",
        "the",
        "heaven",
        "and",
        "earth",
        ",",
        "finally",
        "one",
        "day",
        ",",
        "it",
        "exploded",
        "and",
        "Mosaic",
        "Monkey",
        "-LRB-",
        "M",
        "&",
        "M",
        "in",
        "short",
        "-RRB-",
        "was",
        "borned",
        ".",
    ],
    [
        "This",
        "crappy",
        "ideas",
        "of",
        "mosaic",
        "monkey",
        "-LRB-",
        "inspired",
        "by",
        "Monkey",
        "god",
        "and",
        "crayon",
        "shin",
        "-RRB-",
        "had",
        "been",
        "floating",
        "in",
        "my",
        "mind",
        "for",
        "a",
        "few",
        "months",
        "so",
        "finally",
        "today",
        "i",
        "decided",
        "to",
        "scanned",
        "2",
        "of",
        "sketches",
        "and",
        "make",
        "it",
        "into",
        "a",
        "illustration",
        ".",
    ],
    ["More", "will", "come", ".", ".."],
    [
        "Chapter",
        "two",
        ":",
        "Enter",
        "the",
        "monkeyMosaic",
        "Monkey",
        "decided",
        "to",
        "take",
        "down",
        "all",
        "the",
        "demons",
        "in",
        "the",
        "jungle",
        "to",
        "become",
        "the",
        "King",
        "of",
        "the",
        "jungle",
        ".",
    ],
    ["Kazaaaaa", "!!!"],
    [
        "-LRB-",
        "*",
        "inspired",
        "by",
        "Bruce",
        "lee",
        ":",
        "enter",
        "the",
        "dragon",
        "-RRB-",
        "************************************************************************************Recently",
        ",",
        "i",
        "came",
        "across",
        "a",
        "advertisement",
        "on",
        "a",
        "bus",
        "stop",
        ",",
        "it",
        "wrote",
        "this",
        "\\",
        "No",
        "one",
        "can",
        "survive",
        "on",
        "the",
        "diets",
        "of",
        "hope",
        "!",
    ],
    ["\\", "So", "true", ".", ".."],
    [".."],
    ["Who", "can", "??", "''"],
    [],
    [
        "``",
        "Filed",
        "under",
        ":",
        "AOLTed",
        "checks",
        "in",
        "on",
        "what",
        "people",
        "are",
        "calling",
        "the",
        "\\",
        "data",
        "Valdez",
        ".",
    ],
    [
        "\\",
        "It",
        "so",
        "nice",
        "having",
        "Ted",
        "blogging",
        ",",
        "sometimes",
        "I",
        "feel",
        "like",
        "I",
        "'m",
        "alone",
        "on",
        "the",
        "front",
        "lines",
        ".",
    ],
    [
        "I",
        "wish",
        "other",
        "senior",
        "executives",
        "would",
        "start",
        "blogging",
        "at",
        "AOL",
        "-LRB-",
        "hint",
        ",",
        "hint",
        "-RRB-",
        "--",
        "or",
        "at",
        "least",
        "commenting",
        "-LRB-",
        "you",
        "guys",
        "know",
        "you",
        "can",
        "post",
        "a",
        "comment",
        "to",
        "Ted",
        "'s",
        "blog",
        "or",
        "my",
        "blog",
        "right",
        "?",
        "-RRB-",
    ],
    ["."],
    [
        "I",
        "have",
        "to",
        "be",
        "honest",
        "with",
        "y'all",
        ":",
        "it",
        "'s",
        "hard",
        "times",
        "at",
        "AOL",
        "right",
        "now",
        ",",
        "that",
        "'s",
        "for",
        "sure",
        ".",
    ],
    [
        "Every",
        "couple",
        "of",
        "steps",
        "we",
        "take",
        "going",
        "forward",
        "-LRB-",
        "Netscape",
        ",",
        "TMZ",
        ",",
        "Live8",
        ",",
        "moving",
        "to",
        "the",
        "free",
        "model",
        ",",
        "AIM",
        "Pro",
        ",",
        "AIM",
        "Pages",
        ",",
        "free",
        "five",
        "gigs",
        "of",
        "backup",
        ",",
        "40",
        "%",
        "growth",
        "of",
        "advertising",
        "for",
        "Q2",
        "--",
        "beating",
        "Yahoo",
        ",",
        "MapQuests",
        "API",
        ",",
        "AOL",
        "Uncut",
        "Video",
        "-RRB-",
        ",",
        "we",
        "seem",
        "to",
        "get",
        "hit",
        "back",
        "by",
        "something",
        "horrible",
        "like",
        "he",
        "call",
        "\\",
        "or",
        "he",
        "data",
        "Valdez",
        ".",
    ],
    [
        "\\",
        "The",
        "truth",
        "is",
        "the",
        "company",
        "is",
        "moving",
        "forward",
        ",",
        "but",
        "these",
        "things",
        "create",
        "a",
        "horrible",
        "perception",
        "problem",
        ",",
        "and",
        "it",
        "has",
        "a",
        "real",
        "world",
        "impact",
        "in",
        "that",
        "it",
        "de-motivates",
        "my",
        "teams",
        "and",
        "it",
        "makes",
        "it",
        "so",
        "much",
        "harder",
        "to",
        "get",
        "new",
        "people",
        "into",
        "the",
        "company",
        ".",
    ],
    [
        "Smart",
        "folks",
        "ask",
        "me",
        "about",
        "stuff",
        "like",
        "he",
        "call",
        "\\",
        "when",
        "I",
        "try",
        "to",
        "recruit",
        "them",
        "for",
        "AOL",
        ",",
        "and",
        "I",
        "have",
        "to",
        "assure",
        "them",
        "it",
        "is",
        "n't",
        "gonna",
        "happen",
        "again",
        ".",
    ],
    [
        "It",
        "'s",
        "not",
        "easy",
        ",",
        "and",
        "I",
        "wish",
        "I",
        "could",
        "tell",
        "you",
        "I",
        "always",
        "win",
        "that",
        "fight",
        "--",
        "but",
        "I",
        "do",
        "n't",
        ".",
    ],
    [
        "I",
        "was",
        "so",
        "angry",
        "today",
        "that",
        "I",
        "had",
        "to",
        "get",
        "off",
        "my",
        "computer",
        "and",
        "do",
        "a",
        "three-mile",
        "run",
        ".",
    ],
    [
        "I",
        "'m",
        "back",
        "at",
        "my",
        "desk",
        "but",
        "I",
        "'m",
        "still",
        "seething",
        "--",
        "how",
        "could",
        "this",
        "happen",
        "?",
        "!",
    ],
    [
        "Everyone",
        "is",
        "working",
        "so",
        "hard",
        "to",
        "get",
        "AOL",
        "on",
        "the",
        "right",
        "track",
        ",",
        "and",
        "it",
        "all",
        "gets",
        "forgotten",
        "when",
        "this",
        "kind",
        "of",
        "thing",
        "happens",
        ".",
    ],
    [
        "I",
        "think",
        "I",
        "'m",
        "gonna",
        "take",
        "the",
        "rest",
        "of",
        "the",
        "week",
        "off",
        "from",
        "blogging",
        "as",
        "a",
        "\\",
        "cool",
        "down",
        "\\",
        "period",
        ".",
    ],
    [
        "I",
        "do",
        "n't",
        "want",
        "to",
        "say",
        "something",
        "I",
        "regret",
        ",",
        "and",
        "I",
        "do",
        "n't",
        "want",
        "to",
        "become",
        "the",
        "spokesperson",
        "for",
        "the",
        "entire",
        "company",
        "--",
        "that",
        "'s",
        "not",
        "my",
        "job",
        "and",
        "it",
        "'s",
        "not",
        "my",
        "desire",
        ".",
    ],
    [
        "I",
        "just",
        "want",
        "to",
        "build",
        "cool",
        "stuff",
        "with",
        "cool",
        "people",
        "I",
        "respect",
        ".",
    ],
    [
        "To",
        "my",
        "team",
        "-LRB-",
        "and",
        "everyone",
        "at",
        "AOL",
        "-RRB-",
        ",",
        "keep",
        "fighting",
        "the",
        "good",
        "fight",
        ".",
    ],
    ["Put", "your", "anger", "into", "your", "game", "and", "stay", "focused", "."],
    ["The", "darkest", "hour", "is", "the", "one", "before", "the", "dawn", "."],
    ["We", "'re", "gonna", "get", "through", "this", "."],
    [
        "-LRB-",
        "Note",
        ":",
        "AOL",
        "staffers",
        "can",
        "feel",
        "free",
        "to",
        "post",
        "their",
        "comments",
        "below",
        "--",
        "anonymous",
        "or",
        "on",
        "the",
        "record",
        ".",
    ],
    [
        "I",
        "'ll",
        "turn",
        "them",
        "on",
        "for",
        "you",
        "if",
        "you",
        "use",
        "a",
        "fake",
        "email",
        ".",
    ],
    ["-RRB-"],
    [
        "La",
        "version",
        "RC1",
        "d'Operations",
        "Manager",
        "2007",
        "est",
        "disponible",
        "depuis",
        "http://connect.microsoft.com",
    ],
    [],
    [
        "Les",
        "am\xe9liorations",
        "sur",
        "la",
        "beta",
        "2",
        "sont",
        "les",
        "suivantes",
        ":",
    ],
    [],
    ["\xb7", "Process", "d'installation", "am\xe9lior\xe9"],
    ["\xb7", "Am\xe9liorations", "de", "l'interface", "utilisateur"],
    [
        "\xb7",
        "Mises",
        "\xe0",
        "jour",
        "de",
        "packs",
        "d'administration",
        "et",
        "apparition",
        "du",
        "pack",
        "Active",
        "Directory",
    ],
    [
        "\xb7",
        "Serveur",
        "Gateway",
        "-LRB-",
        "je",
        "tente",
        "la",
        "traduction",
        "de",
        "passerelleJ",
        "-RRB-",
        "et",
        "utilisation",
        "de",
        "certificats",
        "pour",
        "les",
        "p\xe9riph\xe9riques",
        "hors",
        "domaine",
    ],
    [
        "\xb7",
        "Support",
        "d'architecture",
        "utilisant",
        "plusieurs",
        "serveurs",
        "d'administration",
    ],
    ["\xb7", "Am\xe9lioration", "de", "la", "stabilit\xe9"],
    [
        "Les",
        "prochaines",
        "\xe9tapes",
        "visent",
        "un",
        "lancement",
        "mondial",
        "\xe0",
        "San",
        "Diego",
        "lors",
        "du",
        "prochain",
        "Microsoft",
        "Management",
        "Summit",
        "-LRB-",
        "MMS",
        "-RRB-",
        ",",
        "en",
        "mars",
        "prochain",
        ".",
    ],
]

gold_results_all_sentences = [
    [(0, 64, "It'? ?s hard to believe but Dreamforce is less than a week away!")],
    [(64, 94, "In preparation for salesforce.")],
    [
        (
            95,
            206,
            "com'? ?s biggest event of the year, we'? ?ve cataloged all 150 breakout sessions on the Successforce. com site.",
        )
    ],
    [(197, 206, "com site.")],
    [(209, 271, "During the conference you can use this guide to plan your day.")],
    [
        (
            272,
            369,
            "You can navigate by track or choose between the various session offered during a given time slot.",
        )
    ],
    [
        (
            370,
            463,
            "On the session detail pages you'? ?ll find a list of speakers and their respective companies.",
        )
    ],
    [
        (
            464,
            591,
            "We also have a spot where you can leave comments about the session, or post questions you'? ?d like to see the presenter cover.",
        )
    ],
    [(592, 618, "(Dreamforce Comments Feed)")],
    [
        (
            618,
            708,
            "To bring Dreamforce to those who can't make it, we try to post much of the content online.",
        )
    ],
    [
        (
            709,
            843,
            "Last year we had over 50k downloads after the conference, and this year we expect a dramatic increase this year as we introduce video.",
        )
    ],
    [
        (
            844,
            981,
            "In each of the 12 breakout rooms we'? ?ll be recording video so you can connect with the presenter and see all the amazing product demos.",
        )
    ],
    [
        (
            982,
            1104,
            "The first video will be posted on Wednesday October 11th with additional sessions posted to the site as they are produced.",
        )
    ],
    [
        (
            1105,
            1285,
            "For those looking for immediate gratification, we are also planning on posting the PowerPoint slides and other resources referenced in the presentation on the session detail pages.",
        )
    ],
    [(1287, 1323, "We'? ?ve got a fantastic week ahead.")],
    [(1324, 1353, "You won'? ?t want to miss it.")],
    [(1354, 1414, "Make your last minute travel plans and get registered today!")],
    [
        (
            1414,
            1502,
            "Last Friday when the temperature resulted in an \x07ir stagnation alert\\ (I have no idea) .",
        )
    ],
    [
        (
            1503,
            1638,
            "I should have been done on Saturday but had to add those few extra days back in (since the program is based on building on intervals) .",
        )
    ],
    [
        (
            1638,
            1775,
            "I am happy to confirm that I ran for 28 minutes today (well, by running I mean jogging that looks slow but totally rocks my heart rate) .",
        )
    ],
    [
        (
            1776,
            1885,
            "Tomorrow, I run thirty minutes and give myself a pat on the back (it's OK, I'm going to call it stretching) .",
        )
    ],
    [(1887, 1951, "Happy Chinese New YearWishing everyone a HAPPY CHINESE NEW YEAR!")],
    [
        (
            1952,
            2146,
            "Chapter One: Rise of the monkeyFor thousand of years , a stone had been absorbing the\\ki\\ of the heaven and earth , finally one day , it exploded and Mosaic Monkey ( M & M in short ) was borned.",
        )
    ],
    [
        (
            2147,
            2353,
            "This crappy ideas of mosaic monkey (inspired by Monkey god and crayon shin) had been floating in my mind for a few months so finally today i decided to scanned 2 of sketches and make it into a illustration.",
        )
    ],
    [(2354, 2372, "More will come. ..")],
    [
        (
            2374,
            2500,
            "Chapter two: Enter the monkeyMosaic Monkey decided to take down all the demons in the jungle to become the King of the jungle.",
        )
    ],
    [(2501, 2513, "Kazaaaaa! !!")],
    [
        (
            2514,
            2752,
            "(* inspired by Bruce lee: enter the dragon )************************************************************************************Recently, i came across a advertisement on a bus stop, it wrote this \\No one can survive on the diets of hope!",
        )
    ],
    [(2753, 2766, "\\ So true. ..")],
    [(2370, 2372, ".."), (2764, 2766, ".."), (2768, 2770, "..")],
    [(2770, 2783, 'Who can? ?"\n"')],
    [],
    [
        (
            2782,
            2858,
            '"Filed under: AOLTed checks in on what people are calling the  \\data Valdez.',
        )
    ],
    [
        (
            2859,
            2944,
            "\\ It so nice having Ted blogging, sometimes I feel like I'm alone on the front lines.",
        )
    ],
    [
        (
            2945,
            3113,
            "I wish other senior executives would start blogging at AOL (hint, hint) --or at least commenting (you guys know you can post a comment to Ted's blog or my blog right? )",
        )
    ],
    # TODO
    [
        (93, 94, "."),
        (195, 196, "."),
        (205, 206, "."),
        (270, 271, "."),
        (368, 369, "."),
        (462, 463, "."),
        (590, 591, "."),
        (707, 708, "."),
        (842, 843, "."),
        (980, 981, "."),
        (1103, 1104, "."),
        (1284, 1285, "."),
        (1322, 1323, "."),
        (1352, 1353, "."),
        (1501, 1502, "."),
        (1637, 1638, "."),
        (1774, 1775, "."),
        (1884, 1885, "."),
        (2145, 2146, "."),
        (2352, 2353, "."),
        (2368, 2369, "."),
        (2370, 2371, "."),
        (2371, 2372, "."),
        (2372, 2373, "."),
        (2499, 2500, "."),
        (2762, 2763, "."),
        (2764, 2765, "."),
        (2765, 2766, "."),
        (2766, 2767, "."),
        (2768, 2769, "."),
        (2769, 2770, "."),
        (2857, 2858, "."),
        (2943, 2944, "."),
        (3113, 3114, "."),
        (3196, 3197, "."),
        (3499, 3500, "."),
        (3731, 3732, "."),
        (3868, 3869, "."),
        (3949, 3950, "."),
        (4029, 4030, "."),
        (4216, 4217, "."),
        (4302, 4303, "."),
        (4452, 4453, "."),
        (4512, 4513, "."),
        (4577, 4578, "."),
        (4625, 4626, "."),
        (4670, 4671, "."),
        (4700, 4701, "."),
        (4792, 4793, "."),
        (4843, 4844, "."),
        (4925, 4926, "."),
        (4935, 4936, "."),
        (5562, 5563, "."),
    ],
    [
        (
            3115,
            3197,
            "I have to be honest with y'all: it's hard times at AOL right now, that's for sure.",
        )
    ],
    [
        (
            3198,
            3500,
            "Every couple of steps we take going forward (Netscape, TMZ, Live8, moving to the free model, AIM Pro, AIM Pages, free five gigs of backup, 40% growth of advertising for Q2--beating Yahoo, MapQuests API, AOL Uncut Video) , we seem to get hit back by something horrible like \the call\\ or \the data Valdez.",
        )
    ],
    [
        (
            3501,
            3732,
            "\\ The truth is the company is moving forward, but these things create a horrible perception problem, and it has a real world impact in that it de-motivates my teams and it makes it so much harder to get new people into the company.",
        )
    ],
    [
        (
            3733,
            3869,
            "Smart folks ask me about stuff like \the call\\ when I try to recruit them for AOL, and I have to assure them it isn't gonna happen again.",
        )
    ],
    [
        (
            3870,
            3950,
            "It's not easy, and I wish I could tell you I always win that fight--but I don't.",
        )
    ],
    [
        (
            3951,
            4030,
            "I was so angry today that I had to get off my computer and do a three-mile run.",
        )
    ],
    [
        (
            4031,
            4099,
            "I'm back at my desk but I'm still seething--how could this happen? !",
        )
    ],
    [
        (
            4100,
            4217,
            "Everyone is working so hard to get AOL on the right track, and it all gets forgotten when this kind of thing happens.",
        )
    ],
    [
        (
            4218,
            4303,
            "I think I'm gonna take the rest of the week off from blogging as a \\cool down\\period.",
        )
    ],
    [
        (
            4304,
            4453,
            "I don't want to say something I regret, and I don't want to become the spokesperson for the entire company--that's not my job and it's not my desire.",
        )
    ],
    [(4454, 4513, "I just want to build cool stuff with cool people I respect.")],
    [(4514, 4578, "To my team (and everyone at AOL) , keep fighting the good fight.")],
    [(4579, 4626, "Put your anger into your game and stay focused.")],
    [(4627, 4671, "The darkest hour is the one before the dawn.")],
    [(4672, 4701, "We're gonna get through this.")],
    [
        (
            3042,
            3114,
            "(you guys know you can post a comment to Ted's blog or my blog right? ).",
        )
    ],
    [(4794, 4844, "I'll turn them on for you if you use a fake email.")],
    # TODO
    [
        (617, 618, ")"),
        (1499, 1500, ")"),
        (1635, 1636, ")"),
        (1772, 1773, ")"),
        (1882, 1883, ")"),
        (2133, 2134, ")"),
        (2221, 2222, ")"),
        (2557, 2558, ")"),
        (3015, 3016, ")"),
        (3112, 3113, ")"),
        (3416, 3417, ")"),
        (4545, 4546, ")"),
        (5243, 5244, ")"),
        (5543, 5544, ")"),
    ],
    [
        (
            4848,
            4939,
            "La version RC1 d\u2019Operations Manager 2007 est disponible depuis http://connect.microsoft.com",
        )
    ],
    [],
    [(4941, 4993, "Les am\xe9liorations sur la beta 2 sont les suivantes :")],
    [],
    [(4995, 5031, "\xb7         Process d\u2019installation am\xe9")],
    [(5038, 5072, "\xb7         Am\xe9liorations de l\u2019inter")],
    [
        (
            5090,
            5177,
            "\xb7         Mises \xe0 jour de packs d\u2019administration et apparition du pack Active Directory",
        )
    ],
    [
        (
            5179,
            5310,
            "\xb7         Serveur Gateway (je tente la traduction de passerelleJ) et utilisation de certificats pour les p\xe9riph\xe9riques hors domaine",
        )
    ],
    [
        (
            5312,
            5381,
            "\xb7         Support d\u2019architecture utilisant plusieurs serveurs d\u2019admin",
        )
    ],
    [(5392, 5430, "\xb7         Am\xe9lioration de la stabilit\xe9")],
    [
        (
            5432,
            5563,
            "Les prochaines \xe9tapes visent un lancement mondial \xe0 San Diego lors du prochain Microsoft Management Summit (MMS), en mars prochain.",
        )
    ],
]


def test_match_full_sentences():
    for (test_sentence, gold_result) in zip(test_sentences, gold_results_all_sentences):
        sys.stderr.write("gold: " + str(gold_result) + "\n")
        sys.stderr.write("test: " + str(test_sentence) + "\n")
        if sys.version_info[0] >= 3:
            eq_(gold_result, Match.match(test_text, test_sentence))
        else:
            eq_(gold_result, Match.match(test_text.decode("utf8"), test_sentence))
        sys.stderr.write("\n")
