{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name') }}
  version: {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script:
    - cd $SRC_DIR
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - nltk
    - regex


about:
  home: {{ data.get('url') }}
  license: Apache 2.0
  summary: Obtain offsets of tokenizer-standardized clean strings within messy text.
